### ISSUE TITLE
 Get"AttributeError: 'float' object has no attribute 'info'" exception when initializing the gibbs sampler

### ISSUE THREAD

**Issue by dawei-Z** [markgw/gaussianlda#2]
I was trying to implement GaussianLDA to my topic model project, and I got this exception below when I tried to initialize the Gibbs sampler in Google Colab. Is it something wrong with my implementation code?
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-21-3b91a64c0398> in <module>()
      2 
      3 from gaussianlda import GaussianLDATrainer
----> 4 trainer = GaussianLDATrainer(tokenized_corpus, embeddings, vocab, 20, 0.1, 0.1)

/usr/local/lib/python3.6/dist-packages/gaussianlda/trainer/chol.py in __init__(self, corpus, vocab_embeddings, vocab, num_tables, alpha, log, save_path, show_topics, cholesky_decomp, num_words_for_formatting)
    111         self.num_words_for_formatting = num_words_for_formatting
    112 
--> 113         #  self.log.info("Initializing assignments")
    114         self.initialize()
    115 

AttributeError: 'float' object has no attribute 'info

This is my implementation code:
```
from gaussianlda import GaussianLDATrainer
trainer = GaussianLDATrainer(w2v_corpus, embeddings, vocab, 20, 0.1, 0.1)
```
where w2v_corpus is a list of documents where each document is a list of int IDs of words, and embedding is the embedding of each word in the vocab

**Comment by markgw** [comment]
You've got one argument too many - the second 0.1. The kwarg `log` should be a logger, as produced by the `logging` package. Or leave it blank to use a new logger.
