### ISSUE TITLE
trainer.sample hanging at 0%

### ISSUE THREAD

**Issue by khmcnally** [markgw/gaussianlda#3]
Hi there Mark,

I'm toying with this GaussianLDA approach to topic modeling in an industrial setting -- generating topics over business-to-consumer support conversation data.

I am having trouble with getting the trainer.sample function to generate topics. It appears to hang. After an hour or so the first iteration is still at 0% progress. See screenshot attached, not sure if that provides enough context.

Any idea why this might be happening? Or should I just leave it to run for more time, given the size/shape of data? Any help on this would be much appreciated.

<img width="1012" alt="Screenshot 2020-09-22 at 13 41 38" src="https://user-images.githubusercontent.com/1180876/93883601-b13eb100-fcd9-11ea-9a7c-cf1bd669bf2d.png">

**Comment by markgw** [comment]
I have found that the training is very sensitive to the dimensionality of the embeddings. This is unsurprising, as the size of the covariance matrix (and therefore length of the updates) is quadratic in the dimensionality. You could try using smaller embeddings.

But I suspect that it's not that, but rather something to do with iterating over the data. What type is `corpus`? Does it use a generator internally, such that it can only be iterated over once, or something like that? Try iterating over it multiple times and see what happens:
```py
for x in corpus:
    pass
print("Pass 1 complete")
for x in corpus:
    pass
print("Pass 2 complete")```

**Comment by khmcnally** [comment]
Thanks for the reply Mark, and for the help with this.
My corpus is a list of lists, with each inner list containing tuples that represent the (token_id, token_count) according to [gensim's doc2bow function](https://radimrehurek.com/gensim/corpora/dictionary.html#gensim.corpora.dictionary.Dictionary.doc2bow).

<img width="202" alt="Screenshot 2020-09-23 at 11 59 16" src="https://user-images.githubusercontent.com/1180876/94004207-3f776d80-fd94-11ea-970c-2824f035f722.png">

I'm not sure if that answers your question though? In the meantime I will reduce the dimensionality of the embeddings to see if that helps.

As an aside, this data is pretty messy, I have a lot of words that don't make it to the embeddings space due to how I'm generating the embeddings. Lots of say words misspelled once, or strange names, things like that. However the code requires that every word in the corpus must have an embedding. As such, I just artificially created a vector for these words, filled with zeros. I wonder if you have any opinion on that workaround? No problem if not.

**Comment by markgw** [comment]
> I'm not sure if that answers your question though?

It does! The iteration is fine. 

But I think your problem is that the trainer expects a list of lists, where each item is a word ID. So, not a BOWs, but a complete list of word IDs. This is because, unlike Gensim's LDA implementation, it performs Gibbs sampling, so has to iterate over all the words.

Sorry for the lack of documentation on this! I see the doc for the corpus parameter is empty.
Also, it's very weird behaviour – no idea why it just stalls like that.

> I wonder if you have any opinion on that workaround?

This is fine, but it will be a bit more efficient if you simply filter out all out-of-vocabulary words from the training data, instead of adding dummy embeddings.

**Comment by khmcnally** [comment]
Great that makes sense Mark. To be fair, you do say in the docs to do that, I just lazily fired in the corpus in the gensim BOW format.

**Comment by khmcnally** [comment]
That worked, thanks for your help Mark 🙏
