### ISSUE TITLE
Inference with loaded model not covered by documentation

### ISSUE THREAD

**Issue by khmcnally** [markgw/gaussianlda#4]
Hi again Mark,

Now I've actually generated a model, how do I make inferences with it? Maybe I'm just overlooking the readme, or the code itself. Might you have any code snippets I could work from, or even a pointer towards the function that will say, given a document, output the probability distribution of membership of the generated topics?

I appreciate this isn't an issue with the code, please let me know if there's a better way to get in contact.

Thanks in advance!

**Comment by markgw** [comment]
The class you need is `gaussianlda.model.GaussianLda`.

You can load the trained model with `model = GaussianLda.load(path)`, where `path` is the path to the saved model.

Then you can perform inference on a document using: `topics = model.sample(doc, its)`, where `doc` is a single list of word IDs and `its` is a number of sampling iterations. The returned `topics` is a list giving the topic assigned to each word.

Something to be aware of is that any out-of-vocabulary words in `doc` will be ignored, so the topics in `topics` will match up with the list of words _after_ removing OOVs, not necessarily the `doc` given. The safest thing is to filter out OOVs yourself before calling `sample()`.

**Comment by markgw** [comment]
This is indeed a bug, with the documentation. Changed the title and leaving open.

The explanations I've given above should all be covered by the example usage in the README file, which currently says nothing about using a loaded model (even though it tells you how to load it!).

**Comment by khmcnally** [comment]
No problem Mark, that should be plenty for me to work with. 

Apologies for misleading GH issue title, you are dead right to change it.

**Comment by markgw** [comment]
Sorry, my description was slightly wrong:

> where doc is a single list of word IDs 

The doc is actually given as a list of _words_ which are looked up in the vocabulary. (Otherwise the thing I wrote about skipping OOVs wouldn't make any sense!)

**Comment by markgw** [comment]
I've now updated the README to cover this. 

I've also changed `sample()` so that it can instead accept a document as a list of word IDs. If you're already checking for OOVs before sampling, it makes sense to do the mapping too.
